### ISSUE TITLE
(knockout) fix layout issues

### ISSUE THREAD

**Issue by RobbertWolfs** [nerd-labs/mutambo#166] opened 2018-06-19 10:42 UTC
header is not aligned properly anymore
etc...

**Comment by nicolascb** [comment] 2018-06-21 12:37
![image](https://user-images.githubusercontent.com/1793185/41719526-a951cc2a-7536-11e8-9286-9c486c0e79b9.png)

**Comment by WartClaes** [comment] 2018-07-04 08:01
https://app.zeplin.io/project/5b0fa2600b04a1106e04fe7e/screen/5b3c7dba34e882547aee73b5
https://app.zeplin.io/project/5b0fa2600b04a1106e04fe7e/screen/5b3c7dba7d68e72b4651eb88
https://app.zeplin.io/project/5b0fa2600b04a1106e04fe7e/screen/5b3c7dba797abf884b0167da
https://app.zeplin.io/project/5b0fa2600b04a1106e04fe7e/screen/5b3c7db91803daea3fba5c49
https://app.zeplin.io/project/5b0fa2600b04a1106e04fe7e/screen/5b3c7db91853ea0a2ee89f55

**Comment by toxsickcoder** [comment] 2019-07-25 18:21
Looks good to me:

![image](https://user-images.githubusercontent.com/7610043/61898460-a3e13780-af19-11e9-97ea-fbeae0925c40.png)

Possible duplicate of #187?

**Closed** 2019-07-26 06:42 UTC
Labels: bug, comitted
